### ISSUE TITLE
how to set the specific page that using the self cssclasses own self line width, and not affect other obsidian doc's linewidth

### ISSUE THREAD

**Issue by ai-chen2050** [obsidianmd/obsidian-help#631]
I am working on making my homepage, and set its' self cssclasses, .myhome cssstyles, my demand is it own self linewidth showing, and not affect other obsidian doc's linewidth.

I wrote the below code in my myhome.css file, it affect global doc showing。but I just want to change the one doc page, homepage.

how would change the below code to achieve my goals? please help me, thx. all bros.

.myhome, body  {
  --file-line-width: 100% !important;
  --max-width: var(--file-line-width) !important;
  --line-width: var(--file-line-width) !important;
}

**Comment by ai-chen2050** [comment]
btw, I use the minimal theme.

**Comment by alephpiece** [comment]
How about define the class as
```css
.myhome {
    --file-line-width: 100% !important;
    --max-width: var(--file-line-width) !important;
    --line-width: var(--file-line-width) !important;
}
```
in your `myhome.css` file?

Then you should enable this snippet and add a property to your homepage file like this:
![image](https://github.com/obsidianmd/obsidian-help/assets/22237751/a64fb8db-8aaa-415c-b4f0-7315a1048c62)
